Repository redBorder/redborder-serverspec-manager, pull requests merged in 2023-12, with the labels that each got.

#27 Add Serverspec tests for MinIO service and package verification
  spec/services/minio_spec.rb
Labels: size/M, kind/feature

#28 Correction in the format of Directory structure section
  README.md
Labels: documentation, kind/documentation, size/XS

#23 test for f2k service
  spec/services/f2k_spec.rb
Labels: kind/feature, size/S

#34 Add basic test for druid-overlord
  spec/services/druid_overlord_spec.rb
Labels: size/M, kind/feature

#26 redborder-postgresql basic tests
  spec/services/redborder_postgresql_spec.rb
Labels: size/M, kind/feature

#30 Add Serverspec integration test for Webui service
  spec/services/webui_spec.rb
Labels: size/M, kind/feature

#32 Add serverspec integration test for redborder-monitor
  spec/services/redborder_monitor_spec.rb
Labels: size/M, kind/feature

#36 test for nfacctd
  spec/services/nfacctd_spec.rb
Labels: enhancement, size/M

#37 Add basic test for druid-middlemanager
  spec/services/druid_middlemanager_spec.rb
Labels: size/M, kind/feature

#38 Refactored code
  spec/services/druid_broker_spec.rb
Labels: size/M, kind/feature

#40 Add serverspec integration test for rsyslog
  spec/services/rsyslog_spec.rb
Labels: size/S, kind/bug

#42 Fix an error
  spec/services/druid_broker_spec.rb
Labels: size/XS, kind/bug

#45 Modify the name of the service that is registered in consul
  spec/services/chef_spec.rb
Labels: kind/documentation, size/XS

#44 Refactor Mencached Serverspec tests to check if the service is enabled
  spec/services/memcached_spec.rb
Labels: size/M, kind/bug

#41 Refactor Druid Historical Serverspec tests with Consul health check
  spec/services/druid_historical_spec.rb
Labels: size/M, kind/feature

#48 Added mongodb basic test
  spec/services/mongodb_spec.rb
Labels: size/M, kind/feature

#47 Change port to 8001 according to webui.conf
  spec/services/webui_spec.rb
Labels: size/XS, kind/feature

#51 Delete the check for logs in druid-historical
  spec/services/druid_historical_spec.rb
Labels: size/XS, kind/feature

#52 Basic tests for the rb-workers
  spec/services/rb_workers_spec.rb
Labels: kind/feature, size/S

#57 add selinux test
  spec/configuration/selinux_spec.rb
Labels: kind/feature, size/S

#56 Integrate solution to consul registering
  spec/services/consul_spec.rb
  spec/services/druid_broker_spec.rb
  spec/services/druid_coordinator_spec.rb
  spec/services/druid_historical_spec.rb
  spec/services/druid_realtime_spec.rb
  spec/services/f2k_spec.rb
  spec/services/http2k_spec.rb
  spec/services/kafka_spec.rb
  spec/services/memcached_spec.rb
  spec/services/mongodb_spec.rb
  spec/services/nginx_spec.rb
  spec/services/postgresql_spec.rb
  spec/services/rsyslog_spec.rb
  spec/services/webui_spec.rb
  spec/services/zookeeper_spec.rb
Labels: size/L

#63 Add Serverspec tests for redborder-dswatcher service
  spec/services/redborder_dswatcher_spec.rb
Labels: size/M, kind/feature

#61 Added if service_status disabled
  spec/services/mongodb_spec.rb
Labels: size/S, kind/bug

#59 Crond integration test
  spec/services/crond_spec.rb
Labels: size/M, kind/feature

#60 Add serverspec integration tests for logstatter
  spec/services/druid_coordinator_spec.rb
  spec/services/logstatter_spec.rb
Labels: size/M, kind/feature

#65 Add Serverspec tests for rb_boostrap service
  spec/services/rb_bootstrap_spec.rb
Labels: kind/feature, size/S

#53 Feature/ssh test
  README.md
  Rakefile
  spec/services/ssh_spec.rb
Labels: size/M, kind/feature

#64 Add Serverspec tests for serf service
  spec/services/serf_spec.rb
Labels: size/M, kind/feature
