Repository redBorder/redborder-serverspec-manager, pull requests merged in 2023-11, with the labels that each got.

#1 add considerations
  README.md
Labels: kind/documentation, size/XS

#2 Fixing the version of gemfile
  .gitignore
  Gemfile
Labels: kind/documentation, size/XS

#6 Update rubocop.yml
  .github/workflows/rubocop.yml
Labels: kind/documentation, size/S

#5 Basic test for snmp
  spec/services/snmpd_spec.rb
Labels: kind/feature, size/S

#3 Lblanco initial considerations
  .gitignore
  .rspec
  Gemfile
  README.md
  Rakefile
  spec/services/ssh_spec.rb
  spec/spec_helper.rb
Labels: size/M

#4 New test monitor
  Rakefile
  spec/modules/monitor/cluster_monitor_spec.rb
  spec/services/snmpd_spec.rb
  spec/services/ssh_spec.rb
  spec/spec_helper.rb
Labels: kind/feature, size/L

#9 Basic test for druid-realtime
  spec/services/druid_realtime_spec.rb
Labels: kind/feature, size/S

#10 Add integration tests for zookeeper service
  Rakefile
  spec/services/zookeeper_spec.rb
Labels: size/M, kind/feature

#8 Add integration tests for network spec configuration
  spec/configuration/network_spec.rb
Labels: size/M, kind/feature

#12 Add Testing for Druid Historical in druid_historical_spec.rb
  spec/services/druid_historical_spec.rb
Labels: size/M, kind/feature

#16 Add integration test for redborder-monitor
  .gitignore
  spec/services/redborder_monitor_spec.rb
Labels: kind/feature, size/S

#21 Added check for port and register in consul
  spec/services/nginx_spec.rb
Labels: enhancement, kind/feature, size/S

#15 Add memcached_spec.rb with integration test for memcached
  spec/services/memcached_spec.rb
Labels: size/M, kind/feature

#17 Remove date time test in network spec
  spec/configuration/network_spec.rb
Labels: size/S, kind/bug

#14 Add integration test for chef service
  .gitignore
  Rakefile
  spec/services/chef_spec.rb
Labels: size/M, kind/feature

#20 Added http2k, kafka and sfacctd service
  Rakefile
  spec/services/http2k_spec.rb
  spec/services/kafka_spec.rb
  spec/services/sfacctd_spec.rb
  spec/spec_helper.rb
Labels: size/M, kind/feature
