Repository redBorder/redborder-serverspec-manager, pull requests merged in 2024-06, with the labels that each got.

#85 Checks for geoip
  spec/configuration/geoip_spec.rb
Labels: kind/feature, size/S

#75 change vlan from 1 to 0
  spec/spec_helper.rb
Labels: size/XS, kind/feature

#72 check https returns 200 and check the error banner is not in html
  spec/modules/login/webui_spec.rb
Labels: kind/feature, size/S

#86 Revert "check https returns 200 and check the error banner is not in html"
  spec/modules/login/webui_spec.rb
Labels: kind/bug

#88 Bugfix/#17658 fix logstash and ale
  spec/configuration/ale_spec.rb
  spec/services/ale_spec.rb
  spec/services/logstash_spec.rb
Labels: kind/documentation, size/M

#93 set env variable that we are going to read
  spec/spec_helper.rb
Labels: good first issue, kind/documentation, size/XS

#91 Bugfix/17238 logstash not running when no pipelines
  spec/services/logstash_spec.rb
Labels: size/S, kind/bug
