Repository redBorder/redborder-serverspec-manager, pull requests merged in 2024-12, with the labels that each got.

#70 Add redborder_cep_spec.rb
  spec/services/redborder_cep_spec.rb
Labels: size/M, kind/bug

#66 Add motd test
  spec/configuration/motd_spec.rb
Labels: kind/feature, size/S

#87 Bugfix/#17679 by default chef should be up and running
  spec/services/chef_spec.rb
Labels: kind/documentation, size/M

#90 #17692 IS_CLUSTER as env param to skip sync interface and number of nodes
  spec/configuration/network_spec.rb
  spec/spec_helper.rb
Labels: kind/feature, size/S

#82 Bugfix/#17379 check config permisions
  README.md
  spec/configuration/kafka_spec.rb
  spec/configuration/network_spec.rb
Labels: size/M, kind/bug

#104 Bugfix/#19487 remove user login permissions
  spec/services/keepalived_spec.rb
  spec/users/keepalived_spec.rb
Labels: enhancement

#105 Feature/#18893 add firewall test
  spec/configuration/firewall_spec.rb
  spec/services/consul_spec.rb
  spec/services/crond_spec.rb
  spec/services/firewalld_spec.rb
  spec/services/serf_spec.rb
Labels: kind/feature, size/L
