Repository redBorder/redborder-serverspec-manager, pull requests merged in 2024-05, with the labels that each got.

#79 Bugfix/#17236 logstash should stop on no pipelines
  spec/services/logstash_spec.rb
Labels: size/M, kind/bug

#78 Feature/#16519 integrate redborder ale
  spec/configuration/ale_spec.rb
  spec/services/ale_spec.rb
Labels: size/M, kind/feature

#80 postfix health check added
  spec/services/postfix_spec.rb
Labels: enhancement, size/M, kind/feature

#81 rename red to rbcli
  spec/services/ssh_spec.rb
Labels: enhancement, size/XS, kind/feature
